controller_manager:
  ros__parameters:
    update_rate: 30  #Hz

    camdrive_cont:
      type: camdrive_arduino/CamDriveArduinoHardware

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
camdrive_cont:
  ros__parameters:
    device: /dev/ttyUSB0
    baudrate: 57600
    timeout: 100
    enc_counts_per_rev: 400
    loop_rate: 30
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
